import type {
  PlatformRole,
  SchoolRole,
} from "@/generated/prisma/enums";

export const permissions = {
  platformSchoolCreate: "platform:school:create",
  platformSchoolRead: "platform:school:read",
  platformSchoolUpdate: "platform:school:update",
  platformSchoolSuspend: "platform:school:suspend",
  platformSchoolRestore: "platform:school:restore",
  platformPlanManage: "platform:plan:manage",
  platformFeatureFlagManage: "platform:feature-flag:manage",
  platformHealthRead: "platform:health:read",
  platformAuditReadCrossTenant: "platform:audit:read-cross-tenant",
  platformSupportSessionStart: "platform:support-session:start",

  schoolSettingsRead: "school:settings:read",
  schoolSettingsUpdate: "school:settings:update",
  schoolAcademicStructureManage: "school:academic-structure:manage",
  schoolPolicyManage: "school:policy:manage",
  schoolRetentionManage: "school:retention:manage",
  schoolUserRead: "school:user:read",
  schoolUserInvite: "school:user:invite",
  schoolUserImport: "school:user:import",
  schoolUserUpdate: "school:user:update",
  schoolUserSuspend: "school:user:suspend",
  schoolRoleAssign: "school:role:assign",
  schoolReportRead: "school:report:read",
  schoolAuditRead: "school:audit:read",

  mentorDirectoryRead: "mentor:directory:read",
  mentorProfileCreate: "mentor:profile:create",
  mentorProfileUpdate: "mentor:profile:update",
  mentorProfileVerify: "mentor:profile:verify",
  mentorAvailabilityManage: "mentor:availability:manage",
  mentorAppointmentCreate: "mentor:appointment:create",
  mentorAppointmentRead: "mentor:appointment:read",
  mentorAppointmentApprove: "mentor:appointment:approve",
  mentorAppointmentReschedule: "mentor:appointment:reschedule",
  mentorAppointmentCancel: "mentor:appointment:cancel",
  mentorSessionConduct: "mentor:session:conduct",
  mentorSessionNotesWrite: "mentor:session:notes:write",
  mentorSessionNotesRead: "mentor:session:notes:read",
  mentorFeedbackCreate: "mentor:feedback:create",

  resourceRead: "resource:read",
  resourceCreate: "resource:create",
  resourceUpdate: "resource:update",
  resourceSubmitReview: "resource:submit-review",
  resourceReview: "resource:review",
  resourceApprove: "resource:approve",
  resourceReject: "resource:reject",
  resourceVersionCreate: "resource:version:create",
  resourceVersionRollback: "resource:version:rollback",
  resourceDownload: "resource:download",
  resourceCommentCreate: "resource:comment:create",
  resourceReportCreate: "resource:report:create",
  resourceAnalyticsRead: "resource:analytics:read",

  calendarSchoolManage: "calendar:school:manage",
  calendarAvailabilityManage: "calendar:availability:manage",
  calendarEventCreate: "calendar:event:create",
  calendarEventRead: "calendar:event:read",
  calendarEventUpdate: "calendar:event:update",
  calendarEventCancel: "calendar:event:cancel",
  calendarWaitlistManage: "calendar:waitlist:manage",
  calendarAttendanceRecord: "calendar:attendance:record",
  calendarExport: "calendar:export",

  workflowTemplateCreate: "workflow:template:create",
  workflowTemplateRead: "workflow:template:read",
  workflowTemplateUpdateDraft: "workflow:template:update-draft",
  workflowTemplatePublish: "workflow:template:publish",
  workflowTemplateRetire: "workflow:template:retire",
  workflowTemplateReadHistory: "workflow:template:read-history",
  workflowSubmissionCreate: "workflow:submission:create",
  workflowSubmissionRead: "workflow:submission:read",
  workflowSubmissionUpdate: "workflow:submission:update",
  workflowSubmissionWithdraw: "workflow:submission:withdraw",
  workflowSubmissionApprove: "workflow:submission:approve",
  workflowSubmissionReject: "workflow:submission:reject",
  workflowSubmissionRequestChanges:
    "workflow:submission:request-changes",
  workflowSubmissionDelegate: "workflow:submission:delegate",
  workflowSubmissionComment: "workflow:submission:comment",
  workflowAnalyticsRead: "workflow:analytics:read",

  clubCreate: "club:create",
  clubRead: "club:read",
  clubUpdate: "club:update",
  clubApprove: "club:approve",
  clubMembershipApply: "club:membership:apply",
  clubMembershipReview: "club:membership:review",
  clubMembershipManage: "club:membership:manage",
  clubAnnouncementCreate: "club:announcement:create",
  clubEventCreate: "club:event:create",
  clubEventApprove: "club:event:approve",
  clubEventRegister: "club:event:register",
  clubEventAttendance: "club:event:attendance",
  clubBudgetSubmit: "club:budget:submit",
  clubBudgetApprove: "club:budget:approve",
  clubReportSubmit: "club:report:submit",

  messageConversationCreate: "message:conversation:create",
  messageConversationRead: "message:conversation:read",
  messageSend: "message:send",
  messageAttachmentCreate: "message:attachment:create",
  messageDeleteOwn: "message:delete-own",
  commentCreate: "comment:create",
  commentModerate: "comment:moderate",
  notificationReadOwn: "notification:read-own",
  notificationPreferencesUpdateOwn:
    "notification:preferences:update-own",
  notificationSendBroadcast: "notification:send-broadcast",

  auditReadPlatformMetadata: "audit:read-platform-metadata",
  auditReadSchool: "audit:read-school",
  auditExportSchool: "audit:export-school",
  reportExport: "report:export",
} as const;

export type Permission =
  (typeof permissions)[keyof typeof permissions];

const p = permissions;

const commonSchoolPermissions = [
  p.mentorDirectoryRead,
  p.mentorAppointmentRead,
  p.resourceRead,
  p.resourceDownload,
  p.resourceCommentCreate,
  p.resourceReportCreate,
  p.calendarEventRead,
  p.calendarExport,
  p.workflowTemplateRead,
  p.workflowTemplateReadHistory,
  p.workflowSubmissionCreate,
  p.workflowSubmissionRead,
  p.workflowSubmissionUpdate,
  p.workflowSubmissionWithdraw,
  p.workflowSubmissionComment,
  p.clubRead,
  p.clubEventRegister,
  p.messageConversationCreate,
  p.messageConversationRead,
  p.messageSend,
  p.messageAttachmentCreate,
  p.messageDeleteOwn,
  p.commentCreate,
  p.notificationReadOwn,
  p.notificationPreferencesUpdateOwn,
] satisfies Permission[];

export const platformRolePermissions = {
  PLATFORM_SUPER_ADMIN: [
    p.platformSchoolCreate,
    p.platformSchoolRead,
    p.platformSchoolUpdate,
    p.platformSchoolSuspend,
    p.platformSchoolRestore,
    p.platformPlanManage,
    p.platformFeatureFlagManage,
    p.platformHealthRead,
    p.platformAuditReadCrossTenant,
    p.platformSupportSessionStart,
    p.auditReadPlatformMetadata,
  ],
} as const satisfies Record<PlatformRole, readonly Permission[]>;

export const schoolRolePermissions = {
  SCHOOL_ADMIN: [
    ...commonSchoolPermissions,
    p.schoolSettingsRead,
    p.schoolSettingsUpdate,
    p.schoolAcademicStructureManage,
    p.schoolPolicyManage,
    p.schoolRetentionManage,
    p.schoolUserRead,
    p.schoolUserInvite,
    p.schoolUserImport,
    p.schoolUserUpdate,
    p.schoolUserSuspend,
    p.schoolRoleAssign,
    p.schoolReportRead,
    p.schoolAuditRead,
    p.mentorProfileUpdate,
    p.mentorProfileVerify,
    p.mentorAvailabilityManage,
    p.mentorAppointmentCreate,
    p.mentorAppointmentApprove,
    p.mentorAppointmentReschedule,
    p.mentorAppointmentCancel,
    p.mentorFeedbackCreate,
    p.resourceCreate,
    p.resourceUpdate,
    p.resourceSubmitReview,
    p.resourceReview,
    p.resourceApprove,
    p.resourceReject,
    p.resourceVersionCreate,
    p.resourceVersionRollback,
    p.resourceAnalyticsRead,
    p.calendarSchoolManage,
    p.calendarAvailabilityManage,
    p.calendarEventCreate,
    p.calendarEventUpdate,
    p.calendarEventCancel,
    p.calendarWaitlistManage,
    p.calendarAttendanceRecord,
    p.workflowTemplateCreate,
    p.workflowTemplateUpdateDraft,
    p.workflowTemplatePublish,
    p.workflowTemplateRetire,
    p.workflowSubmissionApprove,
    p.workflowSubmissionReject,
    p.workflowSubmissionRequestChanges,
    p.workflowSubmissionDelegate,
    p.workflowAnalyticsRead,
    p.clubCreate,
    p.clubUpdate,
    p.clubApprove,
    p.clubMembershipReview,
    p.clubMembershipManage,
    p.clubAnnouncementCreate,
    p.clubEventCreate,
    p.clubEventApprove,
    p.clubEventAttendance,
    p.clubBudgetSubmit,
    p.clubBudgetApprove,
    p.clubReportSubmit,
    p.commentModerate,
    p.notificationSendBroadcast,
    p.auditExportSchool,
    p.auditReadSchool,
    p.reportExport,
  ],
  TEACHER_STAFF: [
    ...commonSchoolPermissions,
    p.mentorProfileUpdate,
    p.mentorAvailabilityManage,
    p.mentorAppointmentCreate,
    p.mentorAppointmentApprove,
    p.mentorAppointmentReschedule,
    p.mentorAppointmentCancel,
    p.mentorSessionConduct,
    p.mentorSessionNotesWrite,
    p.mentorSessionNotesRead,
    p.mentorFeedbackCreate,
    p.resourceCreate,
    p.resourceUpdate,
    p.resourceSubmitReview,
    p.resourceReview,
    p.resourceApprove,
    p.resourceReject,
    p.resourceVersionCreate,
    p.resourceVersionRollback,
    p.resourceAnalyticsRead,
    p.calendarAvailabilityManage,
    p.calendarEventCreate,
    p.calendarEventUpdate,
    p.calendarEventCancel,
    p.calendarWaitlistManage,
    p.calendarAttendanceRecord,
    p.workflowTemplateCreate,
    p.workflowTemplateUpdateDraft,
    p.workflowTemplatePublish,
    p.workflowTemplateRetire,
    p.workflowSubmissionApprove,
    p.workflowSubmissionReject,
    p.workflowSubmissionRequestChanges,
    p.workflowSubmissionDelegate,
    p.workflowAnalyticsRead,
    p.clubCreate,
    p.clubUpdate,
    p.clubMembershipReview,
    p.clubMembershipManage,
    p.clubAnnouncementCreate,
    p.clubEventCreate,
    p.clubEventAttendance,
    p.clubBudgetSubmit,
    p.clubReportSubmit,
    p.commentModerate,
    p.notificationSendBroadcast,
    p.auditExportSchool,
  ],
  MENTOR_COUNSELOR: [
    ...commonSchoolPermissions,
    p.mentorProfileCreate,
    p.mentorProfileUpdate,
    p.mentorAvailabilityManage,
    p.mentorAppointmentCreate,
    p.mentorAppointmentApprove,
    p.mentorAppointmentReschedule,
    p.mentorAppointmentCancel,
    p.mentorSessionConduct,
    p.mentorSessionNotesWrite,
    p.mentorSessionNotesRead,
    p.resourceCreate,
    p.resourceUpdate,
    p.resourceSubmitReview,
    p.resourceReview,
    p.resourceApprove,
    p.resourceReject,
    p.resourceVersionCreate,
    p.resourceVersionRollback,
    p.calendarAvailabilityManage,
    p.calendarEventCreate,
    p.calendarEventUpdate,
    p.calendarEventCancel,
    p.calendarWaitlistManage,
    p.calendarAttendanceRecord,
    p.workflowSubmissionApprove,
    p.workflowSubmissionReject,
    p.workflowSubmissionRequestChanges,
    p.workflowSubmissionDelegate,
    p.workflowAnalyticsRead,
    p.commentModerate,
  ],
  STUDENT: [
    ...commonSchoolPermissions,
    p.mentorAppointmentCreate,
    p.mentorAppointmentReschedule,
    p.mentorAppointmentCancel,
    p.mentorFeedbackCreate,
    p.resourceCreate,
    p.resourceUpdate,
    p.resourceSubmitReview,
    p.resourceVersionCreate,
    p.resourceAnalyticsRead,
    p.calendarEventCreate,
    p.calendarEventUpdate,
    p.calendarEventCancel,
    p.calendarWaitlistManage,
    p.clubCreate,
    p.clubMembershipApply,
    p.clubAnnouncementCreate,
    p.clubEventCreate,
  ],
  PARENT_GUARDIAN: [
    ...commonSchoolPermissions,
    p.mentorAppointmentCreate,
    p.mentorAppointmentReschedule,
    p.mentorAppointmentCancel,
    p.mentorFeedbackCreate,
    p.resourceCommentCreate,
    p.resourceReportCreate,
    p.calendarEventUpdate,
    p.calendarEventCancel,
    p.calendarWaitlistManage,
    p.clubMembershipApply,
  ],
  CLUB_LEADER: [
    ...commonSchoolPermissions,
    p.resourceCreate,
    p.resourceUpdate,
    p.resourceSubmitReview,
    p.resourceVersionCreate,
    p.resourceAnalyticsRead,
    p.calendarAvailabilityManage,
    p.calendarEventCreate,
    p.calendarEventUpdate,
    p.calendarEventCancel,
    p.calendarWaitlistManage,
    p.calendarAttendanceRecord,
    p.workflowSubmissionApprove,
    p.workflowSubmissionReject,
    p.workflowSubmissionRequestChanges,
    p.workflowAnalyticsRead,
    p.clubCreate,
    p.clubUpdate,
    p.clubMembershipReview,
    p.clubMembershipManage,
    p.clubAnnouncementCreate,
    p.clubEventCreate,
    p.clubEventAttendance,
    p.clubBudgetSubmit,
    p.clubReportSubmit,
    p.commentModerate,
    p.notificationSendBroadcast,
    p.auditExportSchool,
  ],
  APPROVER_REVIEWER: [
    ...commonSchoolPermissions,
    p.mentorProfileVerify,
    p.mentorAppointmentCreate,
    p.mentorAppointmentApprove,
    p.mentorAppointmentReschedule,
    p.mentorAppointmentCancel,
    p.mentorFeedbackCreate,
    p.resourceReview,
    p.resourceApprove,
    p.resourceReject,
    p.calendarEventCreate,
    p.calendarEventUpdate,
    p.calendarEventCancel,
    p.calendarWaitlistManage,
    p.calendarAttendanceRecord,
    p.workflowTemplateCreate,
    p.workflowTemplateUpdateDraft,
    p.workflowTemplatePublish,
    p.workflowTemplateRetire,
    p.workflowSubmissionApprove,
    p.workflowSubmissionReject,
    p.workflowSubmissionRequestChanges,
    p.workflowSubmissionDelegate,
    p.workflowAnalyticsRead,
    p.clubApprove,
    p.clubMembershipReview,
    p.clubMembershipManage,
    p.clubEventApprove,
    p.clubEventAttendance,
    p.clubBudgetSubmit,
    p.clubBudgetApprove,
    p.clubReportSubmit,
    p.commentModerate,
    p.notificationSendBroadcast,
    p.auditExportSchool,
  ],
} as const satisfies Record<SchoolRole, readonly Permission[]>;

export function getSchoolPermissions(
  roles: readonly SchoolRole[],
): Permission[] {
  const effectivePermissions = new Set<Permission>();

  for (const role of roles) {
    for (const permission of schoolRolePermissions[role]) {
      effectivePermissions.add(permission);
    }
  }

  return [...effectivePermissions];
}

export function getPlatformPermissions(
  roles: readonly PlatformRole[],
): Permission[] {
  const effectivePermissions = new Set<Permission>();
  for (const role of roles) {
    for (const permission of platformRolePermissions[role]) {
      effectivePermissions.add(permission);
    }
  }
  return [...effectivePermissions];
}

export function hasPermission(
  effectivePermissions: readonly Permission[],
  permission: Permission,
): boolean {
  return effectivePermissions.includes(permission);
}
